spring.application.name=factures

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=factures
spring.datasource.password=factures123

spring.jpa-show-sql=true
spring.jpa.properties.hibernate.format_sql=true
